export const ACHIEVEMENTS = {
  bindle: {
    id: "bindle",
    name: "Bindle",
    description: "Claimed 3 or more Early Adopter slots. Betting wisdom: questionable. Hustle: undeniable.",
    hint: "???",
    reward: "Swap your balance to 1,500 pts",
    rewardPoints: 1500,
    rewardType: "swap" as const,
    emoji: "🎒",
  },
  lone_wolf: {
    id: "lone_wolf",
    name: "Lone Wolf",
    description: "Won a bet while all other players were betting against you. Outnumbered and undefeated.",
    hint: "???",
    reward: "Earn 400 pts",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🐺",
  },
  bingo: {
    id: "bingo",
    name: "BINGO!",
    description: "First player to complete a bingo line. Called it before anyone else!",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🎱",
  },
  blackout: {
    id: "blackout",
    name: "Blackout!",
    description: "First player to claim every square on their bingo card. Total domination.",
    hint: "???",
    reward: "Earn 750 pts",
    rewardPoints: 750,
    rewardType: "increment" as const,
    emoji: "⬛",
  },
  noble_sacrifice: {
    id: "noble_sacrifice",
    name: "Noble Sacrifice",
    description: "Donated a cumulative 1,000 points or more to Be Cou players. Generosity suits you.",
    hint: "???",
    reward: "1 charge of Thumb on the Scale",
    rewardType: "item" as const,
    rewardItem: "thumb",
    rewardItemUses: 1,
    emoji: "🫀",
  },
} as const;

export type AchievementId = keyof typeof ACHIEVEMENTS;
