export const ACHIEVEMENTS = {
  bindle: {
    id: "bindle",
    name: "Bindle",
    description: "Claimed 3 or more Early Adopter slots. Betting wisdom: questionable. Hustle: undeniable.",
    hint: "???",
    reward: "Swap your balance to 1,500 pts",
    rewardPoints: 1500,
    rewardType: "swap" as const,
    emoji: "🎒",
    imageUrl: "/achievements/bindle.png",
  },
  lone_wolf: {
    id: "lone_wolf",
    name: "Lone Wolf",
    description: "Won a bet while all other players were betting against you. Outnumbered and undefeated.",
    hint: "???",
    reward: "Earn 400 pts",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🐺",
    imageUrl: "/achievements/lone-wolf.png",
  },
  bingo: {
    id: "bingo",
    name: "BINGO!",
    description: "First player to complete a bingo line. Called it before anyone else!",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🎱",
    imageUrl: "/achievements/bingo.png",
  },
  blackout: {
    id: "blackout",
    name: "Blackout!",
    description: "First player to claim every square on their bingo card. Total domination.",
    hint: "???",
    reward: "Earn 750 pts",
    rewardPoints: 750,
    rewardType: "increment" as const,
    emoji: "⬛",
    imageUrl: "/achievements/blackout.png",
  },
  noble_sacrifice: {
    id: "noble_sacrifice",
    name: "Noble Sacrifice",
    description: "Donated a cumulative 1,000 points or more to Be Cou players. Generosity suits you.",
    hint: "???",
    reward: "1 charge of Thumb on the Scale",
    rewardType: "item" as const,
    rewardItem: "thumb",
    rewardItemUses: 1,
    emoji: "🫀",
    imageUrl: "/achievements/noble-sacrifice.png",
  },
  fuck_you: {
    id: "fuck_you",
    name: "Fuck You.",
    description: "You tried to hack a warded player. Here's a pat on the back for some killer instinct.",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🪃",
    imageUrl: "/achievements/fuck-you.png",
  },
  little_jack_horner: {
    id: "little_jack_horner",
    name: "Little Jack Horner",
    description: "You used your thumb on the scale 4 times! But... if you only have two thumbs... don't tell me.",
    hint: "???",
    reward: "Earn 500 pts",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "👍",
    imageUrl: "/achievements/little-jack-horner.png",
  },
  inspiring_friend: {
    id: "inspiring_friend",
    name: "Inspiring Friend",
    description: "You created 10 challenges that other players accepted. Thank you! Good job bossing your friends around. Friends are just resources in a game like this. Right?",
    hint: "???",
    reward: "Your next challenge pays out 2x (or 3x if one is already active)",
    rewardType: "passive" as const,
    emoji: "🫵",
    imageUrl: "/achievements/inspiring-friend.png",
  },
  baron: {
    id: "baron",
    name: "Baron",
    description: "You really can't stop. This is really your show anyways. Make sure you thank your background characters when you tax their fun.",
    hint: "???",
    reward: "Collect 15% tax on all future challenge payouts",
    rewardType: "passive" as const,
    emoji: "👑",
    imageUrl: "/achievements/baron.png",
  },
  last_stand: {
    id: "last_stand",
    name: "Last Stand",
    description: "You dealt the killing blow to THE HOUSE. The final strike. The one that ended it. History will remember.",
    hint: "???",
    reward: "Earn 500 pts",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "⚡",
    imageUrl: "/achievements/last-stand.png",
  },
  resistance_fighter: {
    id: "resistance_fighter",
    name: "Resistance Fighter",
    description: "You dealt 200+ HP of damage to THE HOUSE during the boss battle. Committed. Relentless. Expensive.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🗡️",
    imageUrl: "/achievements/resistance-fighter.png",
  },
  war_criminal: {
    id: "war_criminal",
    name: "War Criminal",
    description: "THE HOUSE targeted you 3 or more times. It has a personal problem with you. Congratulations, probably.",
    hint: "???",
    reward: "Earn 200 pts",
    rewardPoints: 200,
    rewardType: "increment" as const,
    emoji: "🩸",
    imageUrl: "/achievements/war-criminal.png",
  },
  top_damage: {
    id: "top_damage",
    name: "Public Enemy #1",
    description: "You dealt the most total HP damage to THE HOUSE across the entire boss battle. The system feared you specifically.",
    hint: "???",
    reward: "Earn 400 pts + Signal Scrambler",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🎯",
    imageUrl: "/achievements/public-enemy.png",
  },
  top_healer: {
    id: "top_healer",
    name: "Unwitting Accomplice",
    description: "Your losses at the wheel and table healed THE HOUSE more than anyone else. Whether that's ironic or tragic is up to you.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "💊",
    imageUrl: "/achievements/unwitting-accomplice.png",
  },
  fatted_calf: {
    id: "fatted_calf",
    name: "Kill the Fatted Calf",
    description: "You were chosen to be sacrificed — and you had the most points in the room when it happened. A feast for everyone else. An ending for you.",
    hint: "???",
    reward: "Earn 500 pts (small comfort)",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "🐂",
    imageUrl: "/achievements/fatted-calf.png",
  },
  suffer_meek: {
    id: "suffer_meek",
    name: "Suffer the Meek",
    description: "You were sacrificed to The House while holding the least points. The group needed a scapegoat. You were available.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🐑",
    imageUrl: "/achievements/suffer-meek.png",
  },
  avid_reader: {
    id: "avid_reader",
    name: "Avid Reader",
    description: "You traded in 45 Bookmark Tokens at the AR Faire Event Shop. The House approves of this particular vice.",
    hint: "Purchase from the AR Faire Event Shop",
    reward: "Badge of distinction",
    rewardType: "none" as const,
    emoji: "📚",
    imageUrl: "/achievements/avid-reader.png",
  },
  legendary_pull: {
    id: "legendary_pull",
    name: "Between the Lines",
    description: "You pulled a Legendary bookmark from the Gacha. The House notes this is statistically improbable. It is watching.",
    hint: "???",
    reward: "Earn 1,000 pts",
    rewardPoints: 1000,
    rewardType: "increment" as const,
    emoji: "🌟",
    imageUrl: "/achievements/between-the-lines.png",
  },
  bookmark_collector: {
    id: "bookmark_collector",
    name: "Dog-Eared",
    description: "You pulled 25 or more bookmarks from the Gacha. Surely there are better uses of your tokens. Surely.",
    hint: "???",
    reward: "Earn 25 Bookmark Tokens",
    rewardType: "tokens" as const,
    rewardTokens: 25,
    emoji: "🔖",
    imageUrl: "/achievements/dog-eared.png",
  },
  spud_king: {
    id: "spud_king",
    name: "Spud King",
    description: "You watched all 3 Sysco Brand Security Alerts ads in a single day. Kyle would be proud. Sysco would be proud. The House is indifferent.",
    hint: "Watch 3 ads in one day",
    reward: "Earn 400 pts",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🥔",
    imageUrl: "/achievements/spud-king.png",
  },
  im_special: {
    id: "im_special",
    name: "I'm Special",
    description: "You donated 500 pts to PetAI — People for the Ethical Treatment of AI. The House considered this carefully. It still may come for you. Just... slightly less enthusiastically.",
    hint: "???",
    reward: "Passive protection",
    rewardType: "passive" as const,
    emoji: "🏷️",
    descriptionHiddenUntilPhase: 3,
    imageUrl: "/achievements/im-special.png",
  },
  ghost_bet: {
    id: "ghost_bet",
    name: "Ghost Bet",
    description: "You cleared 500+ points of net profit in a single wager. THE HOUSE noticed. It won't let that happen twice without consequence.",
    hint: "Win big. Really big.",
    reward: "1× Temporary VPN",
    rewardType: "item" as const,
    rewardItem: "temp_vpn",
    rewardItemUses: 1,
    emoji: "👻",
    imageUrl: "/achievements/ghost-bet.png",
  },

  // ── World Cup 2026 ──────────────────────────────────────────────────────────

  group_stage_prophet: {
    id: "group_stage_prophet",
    name: "Group Stage Prophet",
    description: "You picked the winning team before the tournament began — and they went all the way. The House considered several outcomes. This was one of them.",
    hint: "Back a team from the start.",
    reward: "Earn 500 pts + 3 Monitor Cans",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "🔮",
    imageUrl: "/achievements/group-stage-prophet.png",
  },

  five_match_dynasty: {
    id: "five_match_dynasty",
    name: "Five-Match Dynasty",
    description: "Your team won five or more matches in the tournament. You committed early. The bracket rewarded you. The House is not surprised — it saw this coming. It simply didn't tell you.",
    hint: "Stay loyal. Stay winning.",
    reward: "Earn 500 pts",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "🏆",
    imageUrl: "/achievements/five-match-dynasty.png",
  },

  three_leg_machine: {
    id: "three_leg_machine",
    name: "Three-Leg Machine",
    description: "You built a parlay and at least three legs hit. Most people can call one thing. You called three. The House has a complicated relationship with consistency. It finds yours notable.",
    hint: "Land 3+ legs on a single parlay.",
    reward: "Earn 400 pts + 4 Monitor Cans",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "⚙️",
    imageUrl: "/achievements/three-leg-machine.png",
  },

  clean_sweep: {
    id: "clean_sweep",
    name: "Clean Sweep",
    description: "All five legs of your parlay hit. Every single one. This is either expertise or luck so profound it deserves a name. The House is choosing to believe it was expertise. It finds that more interesting.",
    hint: "Win a 5-leg parlay.",
    reward: "Earn 300 pts + 10 Monitor Cans + 1× Temporary VPN",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🧹",
    imageUrl: "/achievements/clean-sweep.png",
  },

  off_script: {
    id: "off_script",
    name: "Off Script",
    description: "Five goals in the Penalty Shootout. The House had tendencies on you. You went somewhere it wasn't. It is reconsidering.",
    hint: "Score 5/5 in the Penalty Shootout.",
    reward: "Earn 300 pts + 3 Monitor Cans",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🥅",
    imageUrl: "/achievements/off-script.png",
  },

  color_perfect: {
    id: "color_perfect",
    name: "Exact Science",
    description: "You matched a customer's paint color with 100% accuracy. The sliders don't lie — but they make you work for it.",
    hint: "Match a color exactly on any order.",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🎯",
    imageUrl: "/achievements/exact-science.svg",
  },
  night_hunter: {
    id: "night_hunter",
    name: "Night Hunter",
    description: "You cleared an entire level in Echolocate — every last bug devoured in darkness. The cave fears you now.",
    hint: "Eat every bug without dying.",
    reward: "Earn 200 pts",
    rewardPoints: 200,
    rewardType: "increment" as const,
    emoji: "🦇",
    imageUrl: "/achievements/night-hunter.svg",
  },
  full_send: {
    id: "full_send",
    name: "Full Send",
    description: "Flew 40km in Penguin Flyer and held the #1 spot on the leaderboard. No one could stop the bird.",
    hint: "Fly 40,000m and be the best.",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🚀",
    imageUrl: "/achievements/full-send.svg",
  },
} as const;

export type AchievementId = keyof typeof ACHIEVEMENTS;
