export const ACHIEVEMENTS = {
  bindle: {
    id: "bindle",
    name: "Bindle",
    description: "Claimed 3 or more Early Adopter slots. Betting wisdom: questionable. Hustle: undeniable.",
    hint: "???",
    reward: "Swap your balance to 1,500 pts",
    rewardPoints: 1500,
    rewardType: "swap" as const,
    emoji: "🎒",
  },
  lone_wolf: {
    id: "lone_wolf",
    name: "Lone Wolf",
    description: "Won a bet while all other players were betting against you. Outnumbered and undefeated.",
    hint: "???",
    reward: "Earn 400 pts",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🐺",
  },
  bingo: {
    id: "bingo",
    name: "BINGO!",
    description: "First player to complete a bingo line. Called it before anyone else!",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🎱",
  },
  blackout: {
    id: "blackout",
    name: "Blackout!",
    description: "First player to claim every square on their bingo card. Total domination.",
    hint: "???",
    reward: "Earn 750 pts",
    rewardPoints: 750,
    rewardType: "increment" as const,
    emoji: "⬛",
  },
  noble_sacrifice: {
    id: "noble_sacrifice",
    name: "Noble Sacrifice",
    description: "Donated a cumulative 1,000 points or more to Be Cou players. Generosity suits you.",
    hint: "???",
    reward: "1 charge of Thumb on the Scale",
    rewardType: "item" as const,
    rewardItem: "thumb",
    rewardItemUses: 1,
    emoji: "🫀",
  },
  fuck_you: {
    id: "fuck_you",
    name: "Fuck You.",
    description: "You tried to hack a warded player. Here's a pat on the back for some killer instinct.",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🪃",
  },
  inspiring_friend: {
    id: "inspiring_friend",
    name: "Inspiring Friend",
    description: "You created 10 challenges that other players accepted. Thank you! Good job bossing your friends around. Friends are just resources in a game like this. Right?",
    hint: "???",
    reward: "Your next challenge pays out 2x (or 3x if one is already active)",
    rewardType: "passive" as const,
    emoji: "🫵",
  },
  baron: {
    id: "baron",
    name: "Baron",
    description: "You really can't stop. This is really your show anyways. Make sure you thank your background characters when you tax their fun.",
    hint: "???",
    reward: "Collect 15% tax on all future challenge payouts",
    rewardType: "passive" as const,
    emoji: "👑",
  },
} as const;

export type AchievementId = keyof typeof ACHIEVEMENTS;
