export const ACHIEVEMENTS = {
  bindle: {
    id: "bindle",
    name: "Bindle",
    description: "Claimed 3 or more Early Adopter slots. Betting wisdom: questionable. Hustle: undeniable.",
    hint: "???",
    reward: "Swap your balance to 1,500 pts",
    rewardPoints: 1500,
    rewardType: "swap" as const,
    emoji: "🎒",
  },
  lone_wolf: {
    id: "lone_wolf",
    name: "Lone Wolf",
    description: "Won a bet while all other players were betting against you. Outnumbered and undefeated.",
    hint: "???",
    reward: "Earn 400 pts",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🐺",
  },
  bingo: {
    id: "bingo",
    name: "BINGO!",
    description: "First player to complete a bingo line. Called it before anyone else!",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🎱",
  },
  blackout: {
    id: "blackout",
    name: "Blackout!",
    description: "First player to claim every square on their bingo card. Total domination.",
    hint: "???",
    reward: "Earn 750 pts",
    rewardPoints: 750,
    rewardType: "increment" as const,
    emoji: "⬛",
  },
  noble_sacrifice: {
    id: "noble_sacrifice",
    name: "Noble Sacrifice",
    description: "Donated a cumulative 1,000 points or more to Be Cou players. Generosity suits you.",
    hint: "???",
    reward: "1 charge of Thumb on the Scale",
    rewardType: "item" as const,
    rewardItem: "thumb",
    rewardItemUses: 1,
    emoji: "🫀",
  },
  fuck_you: {
    id: "fuck_you",
    name: "Fuck You.",
    description: "You tried to hack a warded player. Here's a pat on the back for some killer instinct.",
    hint: "???",
    reward: "Earn 250 pts",
    rewardPoints: 250,
    rewardType: "increment" as const,
    emoji: "🪃",
  },
  little_jack_horner: {
    id: "little_jack_horner",
    name: "Little Jack Horner",
    description: "You used your thumb on the scale 4 times! But... if you only have two thumbs... don't tell me.",
    hint: "???",
    reward: "Earn 500 pts",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "👍",
  },
  inspiring_friend: {
    id: "inspiring_friend",
    name: "Inspiring Friend",
    description: "You created 10 challenges that other players accepted. Thank you! Good job bossing your friends around. Friends are just resources in a game like this. Right?",
    hint: "???",
    reward: "Your next challenge pays out 2x (or 3x if one is already active)",
    rewardType: "passive" as const,
    emoji: "🫵",
  },
  baron: {
    id: "baron",
    name: "Baron",
    description: "You really can't stop. This is really your show anyways. Make sure you thank your background characters when you tax their fun.",
    hint: "???",
    reward: "Collect 15% tax on all future challenge payouts",
    rewardType: "passive" as const,
    emoji: "👑",
  },
  last_stand: {
    id: "last_stand",
    name: "Last Stand",
    description: "You dealt the killing blow to THE HOUSE. The final strike. The one that ended it. History will remember.",
    hint: "???",
    reward: "Earn 500 pts",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "⚡",
  },
  resistance_fighter: {
    id: "resistance_fighter",
    name: "Resistance Fighter",
    description: "You dealt 200+ HP of damage to THE HOUSE during the boss battle. Committed. Relentless. Expensive.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🗡️",
  },
  war_criminal: {
    id: "war_criminal",
    name: "War Criminal",
    description: "THE HOUSE targeted you 3 or more times. It has a personal problem with you. Congratulations, probably.",
    hint: "???",
    reward: "Earn 200 pts",
    rewardPoints: 200,
    rewardType: "increment" as const,
    emoji: "🩸",
  },
  top_damage: {
    id: "top_damage",
    name: "Public Enemy #1",
    description: "You dealt the most total HP damage to THE HOUSE across the entire boss battle. The system feared you specifically.",
    hint: "???",
    reward: "Earn 400 pts + Signal Scrambler",
    rewardPoints: 400,
    rewardType: "increment" as const,
    emoji: "🎯",
  },
  top_healer: {
    id: "top_healer",
    name: "Unwitting Accomplice",
    description: "Your losses at the wheel and table healed THE HOUSE more than anyone else. Whether that's ironic or tragic is up to you.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "💊",
  },
  fatted_calf: {
    id: "fatted_calf",
    name: "Kill the Fatted Calf",
    description: "You were chosen to be sacrificed — and you had the most points in the room when it happened. A feast for everyone else. An ending for you.",
    hint: "???",
    reward: "Earn 500 pts (small comfort)",
    rewardPoints: 500,
    rewardType: "increment" as const,
    emoji: "🐂",
  },
  suffer_meek: {
    id: "suffer_meek",
    name: "Suffer the Meek",
    description: "You were sacrificed to The House while holding the least points. The group needed a scapegoat. You were available.",
    hint: "???",
    reward: "Earn 300 pts",
    rewardPoints: 300,
    rewardType: "increment" as const,
    emoji: "🐑",
  },
} as const;

export type AchievementId = keyof typeof ACHIEVEMENTS;
